# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f4b0368c133332ac18527c61f59f21b1133bd7e78a1dc95dcf0b4ac8b4f67c5463ce7a3e45e46795e70f6a79b0b9a40e5bebb23285ac075748a289587ba5b7bc

test:
  secret_key_base: 8484e7fb5ab423bfb82963dd8a3d2c7343ee7326d4e86d3a4f397a5fd69122ce5f8e74e916c699a3e2ead288c64f85e5c522894f15dfcee4a10c72e2a0e26f26

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
